// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dto.proto

package piggy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

type SignUpResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

type AddBankRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBankRequest) Reset()         { *m = AddBankRequest{} }
func (m *AddBankRequest) String() string { return proto.CompactTextString(m) }
func (*AddBankRequest) ProtoMessage()    {}
func (*AddBankRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{2}
}

func (m *AddBankRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBankRequest.Unmarshal(m, b)
}
func (m *AddBankRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBankRequest.Marshal(b, m, deterministic)
}
func (m *AddBankRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBankRequest.Merge(m, src)
}
func (m *AddBankRequest) XXX_Size() int {
	return xxx_messageInfo_AddBankRequest.Size(m)
}
func (m *AddBankRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBankRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBankRequest proto.InternalMessageInfo

type AddBankResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBankResponse) Reset()         { *m = AddBankResponse{} }
func (m *AddBankResponse) String() string { return proto.CompactTextString(m) }
func (*AddBankResponse) ProtoMessage()    {}
func (*AddBankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{3}
}

func (m *AddBankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBankResponse.Unmarshal(m, b)
}
func (m *AddBankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBankResponse.Marshal(b, m, deterministic)
}
func (m *AddBankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBankResponse.Merge(m, src)
}
func (m *AddBankResponse) XXX_Size() int {
	return xxx_messageInfo_AddBankResponse.Size(m)
}
func (m *AddBankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBankResponse proto.InternalMessageInfo

type UpdateBudgetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBudgetRequest) Reset()         { *m = UpdateBudgetRequest{} }
func (m *UpdateBudgetRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBudgetRequest) ProtoMessage()    {}
func (*UpdateBudgetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{4}
}

func (m *UpdateBudgetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBudgetRequest.Unmarshal(m, b)
}
func (m *UpdateBudgetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBudgetRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBudgetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBudgetRequest.Merge(m, src)
}
func (m *UpdateBudgetRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBudgetRequest.Size(m)
}
func (m *UpdateBudgetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBudgetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBudgetRequest proto.InternalMessageInfo

type UpdateBudgetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBudgetResponse) Reset()         { *m = UpdateBudgetResponse{} }
func (m *UpdateBudgetResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBudgetResponse) ProtoMessage()    {}
func (*UpdateBudgetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{5}
}

func (m *UpdateBudgetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBudgetResponse.Unmarshal(m, b)
}
func (m *UpdateBudgetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBudgetResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBudgetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBudgetResponse.Merge(m, src)
}
func (m *UpdateBudgetResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBudgetResponse.Size(m)
}
func (m *UpdateBudgetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBudgetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBudgetResponse proto.InternalMessageInfo

type TagTransactionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagTransactionRequest) Reset()         { *m = TagTransactionRequest{} }
func (m *TagTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TagTransactionRequest) ProtoMessage()    {}
func (*TagTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{6}
}

func (m *TagTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagTransactionRequest.Unmarshal(m, b)
}
func (m *TagTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagTransactionRequest.Marshal(b, m, deterministic)
}
func (m *TagTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagTransactionRequest.Merge(m, src)
}
func (m *TagTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TagTransactionRequest.Size(m)
}
func (m *TagTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagTransactionRequest proto.InternalMessageInfo

type TagTransactionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagTransactionResponse) Reset()         { *m = TagTransactionResponse{} }
func (m *TagTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TagTransactionResponse) ProtoMessage()    {}
func (*TagTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{7}
}

func (m *TagTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagTransactionResponse.Unmarshal(m, b)
}
func (m *TagTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagTransactionResponse.Marshal(b, m, deterministic)
}
func (m *TagTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagTransactionResponse.Merge(m, src)
}
func (m *TagTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TagTransactionResponse.Size(m)
}
func (m *TagTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagTransactionResponse proto.InternalMessageInfo

type StreamTransactionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamTransactionsRequest) Reset()         { *m = StreamTransactionsRequest{} }
func (m *StreamTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamTransactionsRequest) ProtoMessage()    {}
func (*StreamTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{8}
}

func (m *StreamTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamTransactionsRequest.Unmarshal(m, b)
}
func (m *StreamTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *StreamTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamTransactionsRequest.Merge(m, src)
}
func (m *StreamTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamTransactionsRequest.Size(m)
}
func (m *StreamTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamTransactionsRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "piggy.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "piggy.SignUpResponse")
	proto.RegisterType((*AddBankRequest)(nil), "piggy.AddBankRequest")
	proto.RegisterType((*AddBankResponse)(nil), "piggy.AddBankResponse")
	proto.RegisterType((*UpdateBudgetRequest)(nil), "piggy.UpdateBudgetRequest")
	proto.RegisterType((*UpdateBudgetResponse)(nil), "piggy.UpdateBudgetResponse")
	proto.RegisterType((*TagTransactionRequest)(nil), "piggy.TagTransactionRequest")
	proto.RegisterType((*TagTransactionResponse)(nil), "piggy.TagTransactionResponse")
	proto.RegisterType((*StreamTransactionsRequest)(nil), "piggy.StreamTransactionsRequest")
}

func init() { proto.RegisterFile("dto.proto", fileDescriptor_3b9f020a7bf4eafc) }

var fileDescriptor_3b9f020a7bf4eafc = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x29, 0xc9, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xc8, 0x4c, 0x4f, 0xaf, 0x54, 0xe2, 0xe7, 0xe2,
	0x0d, 0xce, 0x4c, 0xcf, 0x0b, 0x2d, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x12, 0xe0,
	0xe2, 0x83, 0x09, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x82, 0x44, 0x1c, 0x53, 0x52, 0x9c, 0x12,
	0xf3, 0xb2, 0x61, 0x6a, 0x04, 0xb9, 0xf8, 0xe1, 0x22, 0x50, 0x45, 0xa2, 0x5c, 0xc2, 0xa1, 0x05,
	0x29, 0x89, 0x25, 0xa9, 0x4e, 0xa5, 0x29, 0xe9, 0xa9, 0x25, 0x30, 0x95, 0x62, 0x5c, 0x22, 0xa8,
	0xc2, 0x50, 0xe5, 0xe2, 0x5c, 0xa2, 0x21, 0x89, 0xe9, 0x21, 0x45, 0x89, 0x79, 0xc5, 0x89, 0xc9,
	0x25, 0x99, 0xf9, 0x79, 0x30, 0x0d, 0x12, 0x5c, 0x62, 0xe8, 0x12, 0x50, 0x2d, 0xd2, 0x5c, 0x92,
	0xc1, 0x25, 0x45, 0xa9, 0x89, 0xb9, 0x48, 0x92, 0xc5, 0x50, 0x6d, 0x4e, 0xfc, 0x51, 0x10, 0xff,
	0x2c, 0x62, 0x62, 0x0d, 0xf0, 0x74, 0x77, 0x8f, 0x4c, 0x62, 0x03, 0xfb, 0xd2, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xac, 0x53, 0xa2, 0x8f, 0xf2, 0x00, 0x00, 0x00,
}
