apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: piggy-api
spec:
  selector:
    matchLabels:
      app: piggy-api
  replicas: 1
  template:
    metadata:
      labels:
        app: piggy-api
    spec:
      containers:
        - name: piggy-api
          image: gcr.io/piggy-police/piggy-api:latest
          ports:
            - containerPort: 80