// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account_AccountType int32

const (
	Account_NONE     Account_AccountType = 0
	Account_CHECKING Account_AccountType = 1
	Account_SAVINGS  Account_AccountType = 2
	Account_CREDIT   Account_AccountType = 3
)

var Account_AccountType_name = map[int32]string{
	0: "NONE",
	1: "CHECKING",
	2: "SAVINGS",
	3: "CREDIT",
}

var Account_AccountType_value = map[string]int32{
	"NONE":     0,
	"CHECKING": 1,
	"SAVINGS":  2,
	"CREDIT":   3,
}

func (x Account_AccountType) String() string {
	return proto.EnumName(Account_AccountType_name, int32(x))
}

func (Account_AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3, 0}
}

type Transaction_Status int32

const (
	Transaction_NONE      Transaction_Status = 0
	Transaction_PENDING   Transaction_Status = 1
	Transaction_CONFIRMED Transaction_Status = 2
)

var Transaction_Status_name = map[int32]string{
	0: "NONE",
	1: "PENDING",
	2: "CONFIRMED",
}

var Transaction_Status_value = map[string]int32{
	"NONE":      0,
	"PENDING":   1,
	"CONFIRMED": 2,
}

func (x Transaction_Status) String() string {
	return proto.EnumName(Transaction_Status_name, int32(x))
}

func (Transaction_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4, 0}
}

type Frequency_Interval int32

const (
	Frequency_NONE    Frequency_Interval = 0
	Frequency_DAILY   Frequency_Interval = 1
	Frequency_WEEKLY  Frequency_Interval = 2
	Frequency_MONTHLY Frequency_Interval = 3
	Frequency_ANNUAL  Frequency_Interval = 4
)

var Frequency_Interval_name = map[int32]string{
	0: "NONE",
	1: "DAILY",
	2: "WEEKLY",
	3: "MONTHLY",
	4: "ANNUAL",
}

var Frequency_Interval_value = map[string]int32{
	"NONE":    0,
	"DAILY":   1,
	"WEEKLY":  2,
	"MONTHLY": 3,
	"ANNUAL":  4,
}

func (x Frequency_Interval) String() string {
	return proto.EnumName(Frequency_Interval_name, int32(x))
}

func (Frequency_Interval) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7, 0}
}

// User of a team. Some users might be the only user of their team.
type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Team is the root hierarchical object that owns the relationship between users/banks/bins
type Team struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Users                []*User   `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Banks                []*Bank   `protobuf:"bytes,4,rep,name=banks,proto3" json:"banks,omitempty"`
	Budgets              []*Budget `protobuf:"bytes,5,rep,name=budgets,proto3" json:"budgets,omitempty"`
	Income               []*Income `protobuf:"bytes,6,rep,name=income,proto3" json:"income,omitempty"`
	FlexBin              *Bin      `protobuf:"bytes,16,opt,name=flex_bin,json=flexBin,proto3" json:"flex_bin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Team) GetBanks() []*Bank {
	if m != nil {
		return m.Banks
	}
	return nil
}

func (m *Team) GetBudgets() []*Budget {
	if m != nil {
		return m.Budgets
	}
	return nil
}

func (m *Team) GetIncome() []*Income {
	if m != nil {
		return m.Income
	}
	return nil
}

func (m *Team) GetFlexBin() *Bin {
	if m != nil {
		return m.FlexBin
	}
	return nil
}

// A financial institution that has been added by a user to a team for tracking purposes.
type Bank struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Accounts             []*Account `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Team                 *Team      `protobuf:"bytes,4,opt,name=team,proto3" json:"team,omitempty"`
	FlexBin              *Bin       `protobuf:"bytes,16,opt,name=flex_bin,json=flexBin,proto3" json:"flex_bin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Bank) Reset()         { *m = Bank{} }
func (m *Bank) String() string { return proto.CompactTextString(m) }
func (*Bank) ProtoMessage()    {}
func (*Bank) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *Bank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bank.Unmarshal(m, b)
}
func (m *Bank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bank.Marshal(b, m, deterministic)
}
func (m *Bank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bank.Merge(m, src)
}
func (m *Bank) XXX_Size() int {
	return xxx_messageInfo_Bank.Size(m)
}
func (m *Bank) XXX_DiscardUnknown() {
	xxx_messageInfo_Bank.DiscardUnknown(m)
}

var xxx_messageInfo_Bank proto.InternalMessageInfo

func (m *Bank) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bank) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bank) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *Bank) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *Bank) GetFlexBin() *Bin {
	if m != nil {
		return m.FlexBin
	}
	return nil
}

// Account within the context of a bank... such as a checking or savings account at chase bank.
type Account struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bank                 *Bank               `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Transactions         []*Transaction      `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Type                 Account_AccountType `protobuf:"varint,5,opt,name=type,proto3,enum=pb.Account_AccountType" json:"type,omitempty"`
	FlexBin              *Bin                `protobuf:"bytes,16,opt,name=flex_bin,json=flexBin,proto3" json:"flex_bin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetBank() *Bank {
	if m != nil {
		return m.Bank
	}
	return nil
}

func (m *Account) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Account) GetType() Account_AccountType {
	if m != nil {
		return m.Type
	}
	return Account_NONE
}

func (m *Account) GetFlexBin() *Bin {
	if m != nil {
		return m.FlexBin
	}
	return nil
}

// Transactions are credits and debits to and from bank accounts.
type Transaction struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string             `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount               int64              `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Account              *Account           `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Status               Transaction_Status `protobuf:"varint,5,opt,name=status,proto3,enum=pb.Transaction_Status" json:"status,omitempty"`
	Bin                  *Bin               `protobuf:"bytes,16,opt,name=bin,proto3" json:"bin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Transaction) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Transaction) GetStatus() Transaction_Status {
	if m != nil {
		return m.Status
	}
	return Transaction_NONE
}

func (m *Transaction) GetBin() *Bin {
	if m != nil {
		return m.Bin
	}
	return nil
}

// Budget serves as the primary top level categorization for budget tracking.
// (Outer Ring Category)
type Budget struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Color                string     `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Amount               string     `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Frequency            *Frequency `protobuf:"bytes,6,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Team                 *Team      `protobuf:"bytes,7,opt,name=team,proto3" json:"team,omitempty"`
	Bins                 []*Bin     `protobuf:"bytes,8,rep,name=bins,proto3" json:"bins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Budget) Reset()         { *m = Budget{} }
func (m *Budget) String() string { return proto.CompactTextString(m) }
func (*Budget) ProtoMessage()    {}
func (*Budget) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *Budget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Budget.Unmarshal(m, b)
}
func (m *Budget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Budget.Marshal(b, m, deterministic)
}
func (m *Budget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Budget.Merge(m, src)
}
func (m *Budget) XXX_Size() int {
	return xxx_messageInfo_Budget.Size(m)
}
func (m *Budget) XXX_DiscardUnknown() {
	xxx_messageInfo_Budget.DiscardUnknown(m)
}

var xxx_messageInfo_Budget proto.InternalMessageInfo

func (m *Budget) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Budget) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Budget) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Budget) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Budget) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Budget) GetFrequency() *Frequency {
	if m != nil {
		return m.Frequency
	}
	return nil
}

func (m *Budget) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *Budget) GetBins() []*Bin {
	if m != nil {
		return m.Bins
	}
	return nil
}

// Bin is the most granular level of categorization for budget tracking.
// (Inner Ring Category)
type Bin struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Budget               *Budget  `protobuf:"bytes,5,opt,name=budget,proto3" json:"budget,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bin) Reset()         { *m = Bin{} }
func (m *Bin) String() string { return proto.CompactTextString(m) }
func (*Bin) ProtoMessage()    {}
func (*Bin) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *Bin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bin.Unmarshal(m, b)
}
func (m *Bin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bin.Marshal(b, m, deterministic)
}
func (m *Bin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bin.Merge(m, src)
}
func (m *Bin) XXX_Size() int {
	return xxx_messageInfo_Bin.Size(m)
}
func (m *Bin) XXX_DiscardUnknown() {
	xxx_messageInfo_Bin.DiscardUnknown(m)
}

var xxx_messageInfo_Bin proto.InternalMessageInfo

func (m *Bin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bin) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Bin) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Bin) GetBudget() *Budget {
	if m != nil {
		return m.Budget
	}
	return nil
}

// Frequency encapsulates the data necessary to track Bin-Budget and Income intervals.
type Frequency struct {
	Unit                 int32              `protobuf:"varint,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Interval             Frequency_Interval `protobuf:"varint,2,opt,name=interval,proto3,enum=pb.Frequency_Interval" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Frequency) Reset()         { *m = Frequency{} }
func (m *Frequency) String() string { return proto.CompactTextString(m) }
func (*Frequency) ProtoMessage()    {}
func (*Frequency) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}

func (m *Frequency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frequency.Unmarshal(m, b)
}
func (m *Frequency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frequency.Marshal(b, m, deterministic)
}
func (m *Frequency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frequency.Merge(m, src)
}
func (m *Frequency) XXX_Size() int {
	return xxx_messageInfo_Frequency.Size(m)
}
func (m *Frequency) XXX_DiscardUnknown() {
	xxx_messageInfo_Frequency.DiscardUnknown(m)
}

var xxx_messageInfo_Frequency proto.InternalMessageInfo

func (m *Frequency) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *Frequency) GetInterval() Frequency_Interval {
	if m != nil {
		return m.Interval
	}
	return Frequency_NONE
}

// Income wraps the necessary data
type Income struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount               string     `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Frequency            *Frequency `protobuf:"bytes,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Team                 *Team      `protobuf:"bytes,5,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Income) Reset()         { *m = Income{} }
func (m *Income) String() string { return proto.CompactTextString(m) }
func (*Income) ProtoMessage()    {}
func (*Income) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{8}
}

func (m *Income) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Income.Unmarshal(m, b)
}
func (m *Income) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Income.Marshal(b, m, deterministic)
}
func (m *Income) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Income.Merge(m, src)
}
func (m *Income) XXX_Size() int {
	return xxx_messageInfo_Income.Size(m)
}
func (m *Income) XXX_DiscardUnknown() {
	xxx_messageInfo_Income.DiscardUnknown(m)
}

var xxx_messageInfo_Income proto.InternalMessageInfo

func (m *Income) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Income) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Income) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Income) GetFrequency() *Frequency {
	if m != nil {
		return m.Frequency
	}
	return nil
}

func (m *Income) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Account_AccountType", Account_AccountType_name, Account_AccountType_value)
	proto.RegisterEnum("pb.Transaction_Status", Transaction_Status_name, Transaction_Status_value)
	proto.RegisterEnum("pb.Frequency_Interval", Frequency_Interval_name, Frequency_Interval_value)
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Team)(nil), "pb.Team")
	proto.RegisterType((*Bank)(nil), "pb.Bank")
	proto.RegisterType((*Account)(nil), "pb.Account")
	proto.RegisterType((*Transaction)(nil), "pb.Transaction")
	proto.RegisterType((*Budget)(nil), "pb.Budget")
	proto.RegisterType((*Bin)(nil), "pb.Bin")
	proto.RegisterType((*Frequency)(nil), "pb.Frequency")
	proto.RegisterType((*Income)(nil), "pb.Income")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0x9b, 0x4a,
	0x14, 0x7d, 0xc0, 0xf0, 0xe1, 0x4b, 0x92, 0x87, 0x46, 0x4f, 0x79, 0x3c, 0xbd, 0xa8, 0xb2, 0x50,
	0xab, 0x5a, 0x8d, 0xe4, 0x85, 0xb3, 0xaf, 0xe4, 0x0f, 0x92, 0xa0, 0x38, 0x24, 0x9a, 0x38, 0xad,
	0xbc, 0xaa, 0x00, 0x4f, 0x2a, 0x14, 0x7b, 0x70, 0x01, 0x57, 0xcd, 0x2f, 0xe8, 0xb2, 0xea, 0xa2,
	0x8b, 0x6e, 0xfb, 0xab, 0xfa, 0x03, 0xfa, 0x27, 0xba, 0xab, 0x66, 0x00, 0x1b, 0x27, 0xa9, 0xc4,
	0xa2, 0xab, 0xc0, 0x39, 0x87, 0xb9, 0xf7, 0x9c, 0x7b, 0x33, 0x06, 0x73, 0x91, 0xcc, 0xe8, 0xbc,
	0xbb, 0x4c, 0x93, 0x3c, 0xc1, 0xf2, 0x32, 0x74, 0x5e, 0x00, 0xba, 0xce, 0x68, 0x8a, 0xf7, 0x40,
	0x8e, 0x67, 0xb6, 0xd4, 0x96, 0x3a, 0x2d, 0x22, 0xc7, 0x33, 0x8c, 0x01, 0xb1, 0x60, 0x41, 0x6d,
	0x59, 0x20, 0xe2, 0xd9, 0xf9, 0x2e, 0x01, 0x9a, 0xd0, 0x60, 0xd1, 0x44, 0x8c, 0x9f, 0x80, 0xba,
	0xca, 0x68, 0x9a, 0xd9, 0x4a, 0x5b, 0xe9, 0x98, 0x3d, 0xa3, 0xbb, 0x0c, 0xbb, 0xbc, 0x12, 0x29,
	0x60, 0xce, 0x87, 0x01, 0xbb, 0xcd, 0x6c, 0xb4, 0xe1, 0x07, 0x01, 0xbb, 0x25, 0x05, 0x8c, 0x9f,
	0x82, 0x1e, 0xae, 0x66, 0x6f, 0x69, 0x9e, 0xd9, 0xaa, 0x50, 0x80, 0x50, 0x08, 0x88, 0x54, 0x14,
	0x76, 0x40, 0x8b, 0x59, 0x94, 0x2c, 0xa8, 0xad, 0x6d, 0x44, 0x9e, 0x40, 0x48, 0xc9, 0x60, 0x07,
	0x8c, 0x9b, 0x39, 0xfd, 0xf0, 0x26, 0x8c, 0x99, 0x6d, 0xb5, 0xa5, 0x8e, 0xd9, 0xd3, 0xc5, 0x51,
	0x31, 0x23, 0x3a, 0x27, 0x06, 0x31, 0x73, 0xbe, 0x48, 0x80, 0x78, 0xf5, 0x46, 0xd6, 0x9e, 0x83,
	0x11, 0x44, 0x51, 0xb2, 0x62, 0x79, 0xe5, 0xce, 0xe4, 0x07, 0xf6, 0x0b, 0x8c, 0xac, 0x49, 0x7c,
	0x00, 0x28, 0xa7, 0xc1, 0xc2, 0x46, 0xa2, 0xaa, 0xb0, 0xc8, 0xf3, 0x23, 0x02, 0x6d, 0xd4, 0xd7,
	0x67, 0x19, 0xf4, 0xf2, 0xdc, 0x46, 0xad, 0x1d, 0x00, 0xe2, 0xf1, 0xd9, 0xca, 0xa6, 0xa2, 0x08,
	0x55, 0xa0, 0xf8, 0x08, 0x76, 0xf2, 0x34, 0x60, 0x59, 0x10, 0xe5, 0x71, 0xc2, 0xaa, 0xe8, 0xff,
	0x16, 0x7d, 0x6d, 0x70, 0xb2, 0x25, 0xc2, 0x87, 0x80, 0xf2, 0xbb, 0x25, 0xb5, 0xd5, 0xb6, 0xd4,
	0xd9, 0xeb, 0xfd, 0x5b, 0x73, 0x5a, 0xfd, 0x9d, 0xdc, 0x2d, 0x29, 0x11, 0xa2, 0x46, 0x9e, 0x5e,
	0x82, 0x59, 0xfb, 0x10, 0x1b, 0x80, 0xfc, 0x0b, 0xdf, 0xb5, 0xfe, 0xc2, 0x3b, 0x60, 0x0c, 0x4f,
	0xdd, 0xe1, 0x99, 0xe7, 0x9f, 0x58, 0x12, 0x36, 0x41, 0xbf, 0xea, 0xbf, 0xf2, 0xfc, 0x93, 0x2b,
	0x4b, 0xc6, 0x00, 0xda, 0x90, 0xb8, 0x23, 0x6f, 0x62, 0x29, 0xce, 0x4f, 0x09, 0xcc, 0x5a, 0xbb,
	0x0f, 0x72, 0x69, 0x83, 0x39, 0xa3, 0x59, 0x94, 0xc6, 0x4b, 0x4e, 0x97, 0xf1, 0xd4, 0x21, 0xbc,
	0x0f, 0x5a, 0xb0, 0xe0, 0x0d, 0x88, 0x9c, 0x14, 0x52, 0xbe, 0xe1, 0x67, 0xa0, 0x97, 0xb3, 0x2b,
	0x47, 0xb6, 0x35, 0xd7, 0x8a, 0xc3, 0x5d, 0xd0, 0xb2, 0x3c, 0xc8, 0x57, 0x59, 0x99, 0xc9, 0xfe,
	0xbd, 0x00, 0xbb, 0x57, 0x82, 0x25, 0xa5, 0x0a, 0xff, 0x07, 0xca, 0x23, 0x79, 0x70, 0xcc, 0xe9,
	0x82, 0x56, 0x88, 0x6b, 0x31, 0x98, 0xa0, 0x5f, 0xba, 0xfe, 0xa8, 0x48, 0x61, 0x17, 0x5a, 0xc3,
	0x0b, 0xff, 0xd8, 0x23, 0xe7, 0xee, 0xc8, 0x92, 0x9d, 0x1f, 0x12, 0x68, 0xc5, 0xff, 0x40, 0xa3,
	0x75, 0xb8, 0x17, 0x85, 0xf2, 0x30, 0x8a, 0x7f, 0x40, 0x8d, 0x92, 0x79, 0x92, 0x0a, 0xc3, 0x2d,
	0x52, 0xbc, 0xd4, 0x02, 0x52, 0x05, 0x5c, 0x05, 0x74, 0x08, 0xad, 0x9b, 0x94, 0xbe, 0x5b, 0x51,
	0x16, 0xdd, 0xd9, 0x9a, 0xf0, 0xb3, 0xcb, 0xfd, 0x1c, 0x57, 0x20, 0xd9, 0xf0, 0xeb, 0xed, 0xd7,
	0x1f, 0xdd, 0xfe, 0xff, 0x01, 0x85, 0x31, 0xcb, 0x6c, 0x43, 0xec, 0xe0, 0x3a, 0x15, 0x01, 0x3a,
	0x1f, 0x25, 0x50, 0x06, 0x31, 0xfb, 0x43, 0x1e, 0x37, 0x6e, 0xd0, 0x96, 0x1b, 0x07, 0xb4, 0xe2,
	0x1e, 0x11, 0x2e, 0xb7, 0x6f, 0x98, 0x92, 0x71, 0xbe, 0x4a, 0xd0, 0x5a, 0xbb, 0xe3, 0xf5, 0x57,
	0x2c, 0xce, 0x45, 0x47, 0x2a, 0x11, 0xcf, 0xb8, 0x07, 0x46, 0xcc, 0x72, 0x9a, 0xbe, 0x0f, 0xe6,
	0xa2, 0xaf, 0x72, 0x1f, 0xd6, 0x1f, 0x75, 0xbd, 0x92, 0x25, 0x6b, 0x9d, 0x33, 0x02, 0xa3, 0x42,
	0x6b, 0x83, 0x6f, 0x81, 0x3a, 0xea, 0x7b, 0xe3, 0xa9, 0x25, 0xf1, 0x7d, 0x7f, 0xed, 0xba, 0x67,
	0xe3, 0xa9, 0x25, 0xf3, 0x7d, 0x38, 0xbf, 0xf0, 0x27, 0xa7, 0xe3, 0xa9, 0xa5, 0x70, 0xa2, 0xef,
	0xfb, 0xd7, 0xfd, 0xb1, 0x85, 0x9c, 0x4f, 0x12, 0x68, 0xc5, 0x5d, 0xd7, 0x28, 0xa8, 0xed, 0xad,
	0xff, 0xcd, 0x50, 0x51, 0xc3, 0xa1, 0xaa, 0x8f, 0x0d, 0x75, 0xa0, 0x7d, 0x93, 0x95, 0xcb, 0x93,
	0x69, 0xa8, 0x89, 0x1f, 0x98, 0xa3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xa7, 0x1f, 0x74,
	0x6f, 0x06, 0x00, 0x00,
}
